import logging
import os
import subprocess
from typing import Dict, Any

from beta_swarm.agents.base import BaseAgent

logger = logging.getLogger(__name__)


class S8TestingAgent(BaseAgent):
    """
    S8: Testing Agent
    Stage 8: Quality Assurance
    Generates pytest unit + integration tests for the FastAPI backend,
    then executes them via subprocess and returns the results.
    """

    def __init__(self, brain=None):
        super().__init__("s8_testing", "Testing Agent", "stage", brain)

    def execute(self, task: Dict[str, Any]) -> Dict[str, Any]:
        project_path = task.get("project_path", "./projects/new_project")

        self._generate_tests(project_path)
        self._generate_conftest(project_path)
        self._generate_e2e_tests(project_path)
        result = self._run_tests(project_path)

        status = "passed" if result.get("passed") else "failed"
        logger.info(f"[S8] Test run {status} (rc={result.get('returncode', '?')})")

        if self.brain:
            self.brain.store_fact(
                self.agent_id,
                f"Tests {status} for {project_path}",
                "testing",
            )

        return {
            "status": "complete",
            "test_results": result,
            "next_stage": "s9_deployment",
        }

    # ------------------------------------------------------------------
    # Test file generators
    # ------------------------------------------------------------------

    def _generate_conftest(self, path: str) -> None:
        code = """\
import pytest
from fastapi.testclient import TestClient
from app.main import app


@pytest.fixture(scope="module")
def client():
    \"\"\"Shared TestClient for all tests in the module.\"\"\"
    with TestClient(app) as c:
        yield c
"""
        test_dir = os.path.join(path, "tests")
        os.makedirs(test_dir, exist_ok=True)
        self._write_file(os.path.join(test_dir, "conftest.py"), code)
        # Ensure tests/ is a package
        init_path = os.path.join(test_dir, "__init__.py")
        if not os.path.exists(init_path):
            self._write_file(init_path, "")

    def _generate_tests(self, path: str) -> None:
        code = """\
\"\"\"
Auto-generated by Beta Swarm S8 — FastAPI backend tests.
\"\"\"
import pytest


# ---------------------------------------------------------------------------
# Health
# ---------------------------------------------------------------------------

def test_health_check(client):
    response = client.get("/health")
    assert response.status_code == 200
    data = response.json()
    assert data["status"] == "healthy"
    assert "version" in data


# ---------------------------------------------------------------------------
# Items — happy paths
# ---------------------------------------------------------------------------

def test_list_items_empty(client):
    response = client.get("/api/v1/items/")
    assert response.status_code == 200
    assert isinstance(response.json(), list)


def test_create_item(client):
    payload = {"title": "Test Item", "user_id": "user-1"}
    response = client.post("/api/v1/items/", json=payload)
    assert response.status_code == 200
    data = response.json()
    assert data["title"] == "Test Item"
    assert data["user_id"] == "user-1"
    assert "id" in data
    assert data["status"] == "active"


def test_get_item(client):
    payload = {"title": "Get Test", "user_id": "user-1"}
    create_resp = client.post("/api/v1/items/", json=payload)
    assert create_resp.status_code == 200
    item_id = create_resp.json()["id"]

    response = client.get(f"/api/v1/items/{item_id}")
    assert response.status_code == 200
    assert response.json()["id"] == item_id


def test_update_item(client):
    payload = {"title": "Original", "user_id": "user-1"}
    create_resp = client.post("/api/v1/items/", json=payload)
    item = create_resp.json()
    item_id = item["id"]

    item["title"] = "Updated"
    update_resp = client.put(f"/api/v1/items/{item_id}", json=item)
    assert update_resp.status_code == 200
    assert update_resp.json()["title"] == "Updated"


def test_delete_item(client):
    payload = {"title": "To Delete", "user_id": "user-1"}
    create_resp = client.post("/api/v1/items/", json=payload)
    item_id = create_resp.json()["id"]

    del_resp = client.delete(f"/api/v1/items/{item_id}")
    assert del_resp.status_code == 200
    assert del_resp.json()["status"] == "deleted"

    # Verify it's gone
    get_resp = client.get(f"/api/v1/items/{item_id}")
    assert get_resp.status_code == 404


# ---------------------------------------------------------------------------
# Items — error paths
# ---------------------------------------------------------------------------

def test_get_nonexistent_item(client):
    response = client.get("/api/v1/items/nonexistent-id")
    assert response.status_code == 404


def test_update_nonexistent_item(client):
    payload = {"title": "Ghost", "user_id": "user-1", "id": "no-such-id"}
    response = client.put("/api/v1/items/no-such-id", json=payload)
    assert response.status_code == 404


def test_delete_nonexistent_item(client):
    response = client.delete("/api/v1/items/no-such-id")
    assert response.status_code == 404


# ---------------------------------------------------------------------------
# Full CRUD round-trip
# ---------------------------------------------------------------------------

def test_full_crud_cycle(client):
    # Create
    payload = {"title": "CRUD Test", "user_id": "user-2"}
    item = client.post("/api/v1/items/", json=payload).json()
    item_id = item["id"]

    # Read
    fetched = client.get(f"/api/v1/items/{item_id}").json()
    assert fetched["title"] == "CRUD Test"

    # Update
    item["title"] = "CRUD Updated"
    updated = client.put(f"/api/v1/items/{item_id}", json=item).json()
    assert updated["title"] == "CRUD Updated"

    # Delete
    client.delete(f"/api/v1/items/{item_id}")
    assert client.get(f"/api/v1/items/{item_id}").status_code == 404
"""
        test_dir = os.path.join(path, "tests")
        os.makedirs(test_dir, exist_ok=True)
        self._write_file(os.path.join(test_dir, "test_api.py"), code)

    def _generate_e2e_tests(self, path: str) -> None:
        """Generates basic Playwright E2E tests."""
        code = """\
import os
import pytest
from playwright.sync_api import sync_playwright

def test_frontend_basic():
    # Use real Playwright E2E testing to verify the generated HTML frontend
    index_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "frontend", "index.html"))
    if not os.path.exists(index_path):
        # If running React, check the build public index
        index_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "frontend", "public", "index.html"))
        
    assert os.path.exists(index_path), "index.html frontend file does not exist"
    
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()
        try:
            page.goto("file://" + index_path)
            # Verify DOM element and visual page title
            assert "Test App" in page.title()
            
            # Click button if it exists
            btn = page.locator("#fetch-btn")
            if btn.count() > 0:
                btn.click()
        finally:
            browser.close()
"""
        test_dir = os.path.join(path, "tests")
        self._write_file(os.path.join(test_dir, "test_e2e.py"), code)

    # ------------------------------------------------------------------
    # Test runner
    # ------------------------------------------------------------------

    def _run_tests(self, path: str) -> Dict:
        """Execute pytest in the project directory and return structured results."""
        try:
            result = subprocess.run(
                ["python", "-m", "pytest", "tests/", "-v", "--tb=short", "--no-header"],
                cwd=path,
                capture_output=True,
                text=True,
                timeout=120,
            )
            return {
                "passed": result.returncode == 0,
                "stdout": result.stdout[-4000:],   # truncate for brain storage
                "stderr": result.stderr[-2000:],
                "returncode": result.returncode,
            }
        except FileNotFoundError:
            logger.warning("[S8] pytest not found — tests written but not executed.")
            return {
                "passed": None,
                "stdout": "",
                "stderr": "pytest not installed in current environment.",
                "returncode": -1,
            }
        except subprocess.TimeoutExpired:
            return {
                "passed": False,
                "stdout": "",
                "stderr": "Test run timed out after 120 seconds.",
                "returncode": -2,
            }
        except Exception as e:
            return {"passed": False, "error": str(e), "returncode": -3}

    # ------------------------------------------------------------------

    @staticmethod
    def _write_file(path: str, content: str) -> None:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
