"""
Auto-generated by Beta Swarm S8 — FastAPI backend tests.
"""
import pytest


# ---------------------------------------------------------------------------
# Health
# ---------------------------------------------------------------------------

def test_health_check(client):
    response = client.get("/health")
    assert response.status_code == 200
    data = response.json()
    assert data["status"] == "healthy"
    assert "version" in data


# ---------------------------------------------------------------------------
# Items — happy paths
# ---------------------------------------------------------------------------

def test_list_items_empty(client):
    response = client.get("/api/v1/items/")
    assert response.status_code == 200
    assert isinstance(response.json(), list)


def test_create_item(client):
    payload = {"title": "Test Item", "user_id": "user-1"}
    response = client.post("/api/v1/items/", json=payload)
    assert response.status_code == 200
    data = response.json()
    assert data["title"] == "Test Item"
    assert data["user_id"] == "user-1"
    assert "id" in data
    assert data["status"] == "active"


def test_get_item(client):
    payload = {"title": "Get Test", "user_id": "user-1"}
    create_resp = client.post("/api/v1/items/", json=payload)
    assert create_resp.status_code == 200
    item_id = create_resp.json()["id"]

    response = client.get(f"/api/v1/items/{item_id}")
    assert response.status_code == 200
    assert response.json()["id"] == item_id


def test_update_item(client):
    payload = {"title": "Original", "user_id": "user-1"}
    create_resp = client.post("/api/v1/items/", json=payload)
    item = create_resp.json()
    item_id = item["id"]

    item["title"] = "Updated"
    update_resp = client.put(f"/api/v1/items/{item_id}", json=item)
    assert update_resp.status_code == 200
    assert update_resp.json()["title"] == "Updated"


def test_delete_item(client):
    payload = {"title": "To Delete", "user_id": "user-1"}
    create_resp = client.post("/api/v1/items/", json=payload)
    item_id = create_resp.json()["id"]

    del_resp = client.delete(f"/api/v1/items/{item_id}")
    assert del_resp.status_code == 200
    assert del_resp.json()["status"] == "deleted"

    # Verify it's gone
    get_resp = client.get(f"/api/v1/items/{item_id}")
    assert get_resp.status_code == 404


# ---------------------------------------------------------------------------
# Items — error paths
# ---------------------------------------------------------------------------

def test_get_nonexistent_item(client):
    response = client.get("/api/v1/items/nonexistent-id")
    assert response.status_code == 404


def test_update_nonexistent_item(client):
    payload = {"title": "Ghost", "user_id": "user-1", "id": "no-such-id"}
    response = client.put("/api/v1/items/no-such-id", json=payload)
    assert response.status_code == 404


def test_delete_nonexistent_item(client):
    response = client.delete("/api/v1/items/no-such-id")
    assert response.status_code == 404


# ---------------------------------------------------------------------------
# Full CRUD round-trip
# ---------------------------------------------------------------------------

def test_full_crud_cycle(client):
    # Create
    payload = {"title": "CRUD Test", "user_id": "user-2"}
    item = client.post("/api/v1/items/", json=payload).json()
    item_id = item["id"]

    # Read
    fetched = client.get(f"/api/v1/items/{item_id}").json()
    assert fetched["title"] == "CRUD Test"

    # Update
    item["title"] = "CRUD Updated"
    updated = client.put(f"/api/v1/items/{item_id}", json=item).json()
    assert updated["title"] == "CRUD Updated"

    # Delete
    client.delete(f"/api/v1/items/{item_id}")
    assert client.get(f"/api/v1/items/{item_id}").status_code == 404
