from beta_swarm.agents.base import BaseAgent
from typing import Dict, Any
import os

class DocumentationAgent(BaseAgent):
    def __init__(self, brain=None):
        super().__init__("u4_docs", "Documentation", "Utility: Docs Generation", brain)

    def execute(self, task: Dict[str, Any]) -> Dict[str, Any]:
        project_path = task.get("project_path", "./projects/new_project")
        doc_type = task.get("doc_type", "readme")

        # IMPROVEMENT: Ensure the project_path directory exists to prevent FileNotFoundError
        # when trying to open/write files to a directory that the frontend/backend stages might not have fully created.
        os.makedirs(project_path, exist_ok=True)

        if doc_type == "readme":
            readme = '''# Project\n\nGenerated by Beta Swarm.\n\n## Setup\n\n```bash\npip install -r requirements.txt\npython -m app.main\n```\n\n## API\n\nSee `API.md` for endpoint documentation.\n'''
            with open(os.path.join(project_path, "README.md"), "w") as f:
                f.write(readme)
            return {"status": "complete", "file": f"{project_path}/README.md"}

        elif doc_type == "api_docs":
            api_md = '''# API Documentation\n\n## Endpoints\n\n- `GET /health` — Health check\n- `GET /api/v1/items` — List items\n- `POST /api/v1/items` — Create item\n- `GET /api/v1/items/{id}` — Get item\n- `PUT /api/v1/items/{id}` — Update item\n- `DELETE /api/v1/items/{id}` — Delete item\n'''
            with open(os.path.join(project_path, "API.md"), "w") as f:
                f.write(api_md)
            return {"status": "complete", "file": f"{project_path}/API.md"}

        elif doc_type == "architecture":
            arch_md = '''# Architecture\n\n## Components\n\n- API Gateway (Traefik)\n- Auth Service (JWT)\n- Core API (FastAPI)\n- Database (PostgreSQL)\n- Frontend (React)\n- AI Worker (LM Studio)\n\n## Data Flow\n\nClient → Traefik → Auth → Core API → Database\n                    ↓\n                 AI Worker\n'''
            with open(os.path.join(project_path, "ARCHITECTURE.md"), "w") as f:
                f.write(arch_md)
            return {"status": "complete", "file": f"{project_path}/ARCHITECTURE.md"}

        else:
            return {"status": "error", "message": f"Unknown doc_type: {doc_type}"}

# Alias for compatibility with compliance checks and testing
U4DocumentationAgent = DocumentationAgent

