#!/usr/bin/env bash
# Auto-generated by Beta Swarm S9
# Usage: ./deploy.sh [--pull]
set -euo pipefail

PULL=${1:-}

echo "=== Beta Swarm — Deployment Script ==="
echo "Target directory: $(pwd)"

# Load environment variables if .env exists
if [ -f .env ]; then
  echo "[+] Loading .env"
  set -a; source .env; set +a
fi

if [ "$PULL" = "--pull" ]; then
  echo "[+] Pulling latest images..."
  docker-compose pull
fi

echo "[+] Bringing down existing services..."
docker-compose down --remove-orphans || true

echo "[+] Building images..."
docker-compose build --no-cache

echo "[+] Starting services..."
docker-compose up -d

echo "[+] Waiting for health checks..."
sleep 5
docker-compose ps

echo "=== Deployment Complete ==="
echo "App:      http://localhost:8000"
echo "Frontend: http://localhost:3000"
echo "Docs:     http://localhost:8000/docs"
